services:
  db:
    image: mysql:8.0
    container_name: prolead-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/nest/Dockerfile
    container_name: prolead-back
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: ../docker/next/Dockerfile
    container_name: prolead-client
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  mysql_data:
